# Generated by Django 4.2.3 on 2023-07-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancies', models.IntegerField()),
                ('glucose', models.IntegerField()),
                ('bloodPressure', models.IntegerField()),
                ('skinThickness', models.IntegerField()),
                ('insulin', models.IntegerField()),
                ('diabetesPedigreeFunction', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('Age', models.IntegerField()),
            ],
        ),
    ]
