# Generated by Django 4.2.3 on 2023-07-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_alter_surveyinfo_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyinfo',
            old_name='bloodPressure',
            new_name='BloodPressure',
        ),
        migrations.RenameField(
            model_name='surveyinfo',
            old_name='diabetesPedigreeFunction',
            new_name='DiabetesPedigreeFunction',
        ),
        migrations.RenameField(
            model_name='surveyinfo',
            old_name='glucose',
            new_name='Glucose',
        ),
        migrations.RenameField(
            model_name='surveyinfo',
            old_name='insulin',
            new_name='Insulin',
        ),
        migrations.RenameField(
            model_name='surveyinfo',
            old_name='pregnancies',
            new_name='Pregnancies',
        ),
    ]
