# Generated by Django 4.2.3 on 2023-07-13 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0005_rename_bloodpressure_surveyinfo_bloodpressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyinfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
