# Generated by Django 4.2.3 on 2023-07-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_alter_surveyinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyinfo',
            name='DiabetesPedigreeFunction',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='surveyinfo',
            name='weight',
            field=models.FloatField(),
        ),
    ]
