# Generated by Django 4.2.3 on 2023-07-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_alter_surveyinfo_diabetespedigreefunction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyinfo',
            name='isTrain',
            field=models.BooleanField(default=False),
        ),
    ]
