# Generated by Django 4.2.3 on 2023-07-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_alter_surveyinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyinfo',
            name='height',
            field=models.FloatField(),
        ),
    ]
