# Generated by Django 4.2.3 on 2023-07-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_alter_surveyinfo_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyinfo',
            name='isTest',
            field=models.BooleanField(default=False),
        ),
    ]
