# Generated by Django 4.2.3 on 2023-07-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_surveyinfo_istest'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyinfo',
            name='isNotInput',
            field=models.BooleanField(default=False),
        ),
    ]
